gemma-2-9b-it-gmsimpo-beta10-gm0.5-tau20-lr8e-7:
  completions_kwargs:
    batch_size: 900
    do_sample: true
    max_new_tokens: 4096
    model_kwargs:
      torch_dtype: bfloat16
    model_name: outputs/gemma-2-9b-it-gmsimpo-beta10-gm0.5-tau20-lr8e-7
    stop_token_ids:
    - 1
    - 107
    temperature: 0.5
    top_p: 1.0
  fn_completions: vllm_local_completions
  pretty_name: gemma-2-9b-it-gmsimpo-beta10-gm0.5-tau20-lr8e-7
  prompt_template: eval/alpacaeval2/template/gemma2.txt
