qwen-2.5-7b-it-gmsimpo-beta10-gm0.3-tau3-lr1e-6:
  completions_kwargs:
    batch_size: 900
    do_sample: true
    max_new_tokens: 4096
    model_kwargs:
      torch_dtype: bfloat16
    model_name: outputs/qwen-2.5-7b-it-gmsimpo-beta10-gm0.3-tau3-lr1e-6
    stop_token_ids: 
    - 151645
    temperature: 0.5
    top_p: 1.0
  fn_completions: vllm_local_completions
  pretty_name: qwen-2.5-7b-it-gmsimpo-beta10-gm0.3-tau3-lr1e-6
  prompt_template: eval/alpacaeval2/template/qwen2_instruct.txt